source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

def reusepods
end

def testpods
  pod 'Nimble'
  pod 'Quick'
end

target '{{ cookiecutter.name }}' do
  reusepods
end

target '{{ cookiecutter.testname }}' do
  reusepods
  testpods
end
